In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import time
import matplotlib.dates as mdates
import seaborn as sns
import matplotlib.pyplot as plt
from pandasql import *
import seaborn as sns
import warnings
from numpy import *
from sklearn.metrics import accuracy_score
from sklearn.ensemble import IsolationForest
import math
from sklearn.metrics import mean_squared_error
from math import sqrt
from time import time
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import NMF
warnings.filterwarnings('ignore')
%matplotlib inline

In [5]:
df_train = pd.read_csv("train_data.csv")
df_test = pd.read_csv("test_data.csv")

In [6]:
df_train.shape

(21, 2)

In [8]:
df_train.head(25)

title                                            content
0     albert einstein  \nalbert einstein ( ; ; 14 march 1879â â€“ 18 ...
1        lionel messi  \nlionel andrã©s messi cuccittini (; born 24 j...
2        isaac newton  \nsir isaac newton (25 december 1642â â€“ 20 m...
3        barack obama  \nbarack hussein obama ii (; born august 4, 19...
4      vladimir putin  \nvladimir vladimirovich putin (; ; born 7 oct...
5     maria sharapova  \nmaria yuryevna sharapova (; born april 19, 1...
6          steve jobs  \nsteven paul jobs (; february 24, 1955 – oc...
7      charles darwin  \ncharles robert darwin, (; 12 february 1809â ...
8    sachin tendulkar  \nsachin ramesh tendulkar (; born 24 april 197...
9       narendra modi  \nnarendra damodardas modi (; born 17 septembe...
10  leonardo dicaprio  \nleonardo wilhelm dicaprio (, ; born november...
11       andre agassi  \nandre kirk agassi ( ; born april 29, 1970) i...
12         larry page  \nlawrence edward page (born march 26, 1973) i...
13   amitabh bachchan  \namitabh bachchan (; born inquilaab srivastav...
14         ed sheeran  \nedward christopher sheeran, (; born 17 febru...
15         bill gates  \nwilliam henry gates iii (born october 28, 19...
16     alan greenspan  \nalan greenspan (; born march 6, 1926) is an ...
17   dmitri mendeleev  \ndmitri ivanovich mendeleev (often romanized ...
18          gal gadot  \ngal gadot varsano (, ; born 30 april 1985) i...
19    geoffrey hinton  \ngeoffrey everest hinton (born 6 december 194...
20           sal khan  \nsalman “sal” khan (born october 11, 1976...

In [5]:
df_test.shape

(25, 2)

In [6]:
df_test.head()

title                                            content
0       abraham lincoln  \nabraham lincoln (february 12, 1809 – april...
1  atal bihari vajpayee  \natal bihari vajpayee (; 25 december 1924 –...
2        justin trudeau  \njustin pierre james trudeau (; ; born decemb...
3       stephen hawking  \nstephen william hawking (8 january 1942 – ...
4        nelson mandela  \nnelson rolihlahla mandela (; ; 18 july 1918â...

In [12]:
# Use tf-idf features for NMF.
print("Extracting count vectoriser features for NMF...")
count_vectorizer = CountVectorizer(max_df=0.95, min_df=2,
                                   stop_words='english')
t0 = time()
count_vec = count_vectorizer.fit_transform(df_train['content'])
print("done in %0.3fs." % (time() - t0))

Extracting tf-idf features for NMF...
done in 0.119s.


In [13]:
count_vectorizer.vocabulary_

{'albert': 516,
 'einstein': 2064,
 '14': 40,
 'march': 3531,
 '18': 57,
 'april': 640,
 '1955': 113,
 'german': 2628,
 'theoretical': 5614,
 'physicist': 4201,
 'developed': 1810,
 'theory': 5616,
 'relativity': 4700,
 'modern': 3702,
 'physics': 4203,
 'alongside': 548,
 'quantum': 4517,
 'mechanics': 3602,
 'work': 6060,
 'known': 3279,
 'influence': 3038,
 'philosophy': 4191,
 'science': 4975,
 'best': 894,
 'general': 2612,
 'public': 4483,
 'energy': 2130,
 'formula': 2514,
 'dubbed': 1995,
 'world': 6067,
 'famous': 2354,
 'nobel': 3848,
 'prize': 4388,
 'services': 5059,
 'especially': 2196,
 'discovery': 1874,
 'law': 3325,
 'effect': 2051,
 'pivotal': 4215,
 'step': 5338,
 'development': 1814,
 'near': 3799,
 'beginning': 865,
 'career': 1103,
 'thought': 5627,
 'newtonian': 3834,
 'longer': 3441,
 'reconcile': 4626,
 'laws': 3328,
 'classical': 1266,
 'field': 2414,
 'led': 3352,
 'develop': 1809,
 'special': 5246,
 'swiss': 5509,
 'patent': 4101,
 'office': 3920,
 '1909': 8

In [14]:
n_components = 100
nmf = NMF(n_components=n_components, random_state=1,
          alpha=.1, l1_ratio=.5)
W_train = nmf.fit_transform(count_vec)
H_train = nmf.components_

In [15]:
W_train.shape

(21, 100)

In [16]:
H_train.shape

(100, 6107)

In [17]:
W_train

array([[1.59799349e-02, 0.00000000e+00, 6.73667085e+00, ...,
        0.00000000e+00, 0.00000000e+00, 2.73017302e+00],
       [8.25417723e+00, 0.00000000e+00, 3.37638407e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.66560976e-04, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.59314473e-03, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.91143793e-05, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [18]:
H_train

array([[5.62795675e-01, 0.00000000e+00, 2.55691636e-04, ...,
        2.51084771e-04, 2.59537067e-04, 0.00000000e+00],
       [2.43588273e-02, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 6.08141251e-02],
       [2.22281306e-01, 0.00000000e+00, 0.00000000e+00, ...,
        2.16207236e-04, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.34128786e-01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 6.84265777e-01]])

In [19]:
W_train.dot(H_train)

array([[3.97556696e+00, 3.36304492e-03, 4.94691252e-05, ...,
        1.50600182e-03, 1.21288212e-04, 4.96915460e+00],
       [6.97675251e+00, 1.91017772e-03, 9.88289070e-01, ...,
        9.88285601e-01, 9.88285263e-01, 0.00000000e+00],
       [2.99414769e+00, 1.81896740e-05, 1.16122286e-04, ...,
        9.56129601e-06, 8.34904084e-05, 3.07836191e-03],
       ...,
       [4.72126627e-03, 1.20794029e-05, 4.18800315e-05, ...,
        1.59433541e-04, 4.19956146e-05, 1.29524323e-04],
       [2.04821550e-03, 3.83244120e-06, 1.06536430e-05, ...,
        6.30375237e-05, 4.64654862e-05, 1.31941048e-04],
       [1.61799902e-03, 4.13728985e-06, 2.04370042e-05, ...,
        1.16068905e-04, 4.35388109e-05, 1.56738402e-05]])

In [20]:
count_vec_test = count_vectorizer.transform(df_test['content'])

In [21]:
count_vec_test

<25x6107 sparse matrix of type '<class 'numpy.int64'>'
	with 24654 stored elements in Compressed Sparse Row format>

In [22]:
W = nmf.transform(count_vec_test)
H = nmf.components_



In [23]:
W.shape

(25, 100)

In [24]:
H.shape

(100, 6107)

In [25]:
lst = []
cols = []
for i in range(1,101):
    cols.append("val_" + str(i))
for index, row in df_train.iterrows():
    tmp = [row['title']]
    for i in range(100):
        tmp.append(W_train[index][i])
    lst.append(tmp)

In [26]:
df_train_embedding = pd.DataFrame(lst, columns=['title'] + cols)

In [27]:
df_train_embedding.head()

title     val_1     val_2     val_3      val_4      val_5  \
0  albert einstein  0.015980  0.000000  6.736671  12.564926   0.019296   
1     lionel messi  8.254177  0.000000  3.376384   0.000000   0.037524   
2     isaac newton  0.000367  0.000000  0.000000   5.500924   0.000704   
3     barack obama  0.017073  0.000000  5.155706   0.095018   0.636230   
4   vladimir putin  0.036630  0.012976  5.322053   0.183029  22.426821   

      val_6     val_7     val_8      val_9  ...    val_91    val_92    val_93  \
0  0.000000  0.000000  0.032997   0.006249  ...  0.000000  0.000000  0.000000   
1  0.435125  0.025223  0.010464   0.001191  ...  0.000000  0.000000  2.395634   
2  0.009777  0.001112  0.000000  10.554753  ...  0.000000  0.000000  0.000000   
3  0.518208  0.000000  0.000000   0.000007  ...  0.000000  0.000000  0.000000   
4  0.034125  0.000000  0.034620   0.000076  ...  0.000735  0.990574  0.000000   

   val_94  val_95  val_96  val_97  val_98  val_99   val_100  
0     0.0     0.0     0.0     0.0     0.0     0.0  2.730173  
1     0.0     0.0     0.0     0.0     0.0     0.0  0.000000  
2     0.0     0.0     0.0     0.0     0.0     0.0  0.000000  
3     0.0     0.0     0.0     0.0     0.0     0.0  0.000000  
4     0.0     0.0     0.0     0.0     0.0     0.0  0.000000  

[5 rows x 101 columns]

In [28]:
artists = ["Leonardo DiCaprio","Amitabh Bachchan","Gal Gadot","Ed Sheeran"]
artists = [ppl.lower() for ppl in artists]

sportsPerson =  ["Andre Agassi","Maria Sharapova","Sachin Tendulkar","Lionel Messi"]
sportsPerson = [ppl.lower() for ppl in sportsPerson]

politicians = ["Barack Obama","Narendra Modi","Vladimir Putin"]
politicians = [ppl.lower() for ppl in politicians]

scientists = ["Albert Einstein","Isaac Newton","Dmitri Mendeleev","Charles Darwin"]
scientists = [ppl.lower() for ppl in scientists]

influencers = ["Steve Jobs","Larry Page",
             "Bill Gates","Alan Greenspan","Sal Khan","Geoffrey Hinton"]
influencers = [ppl.lower() for ppl in influencers]

In [29]:
embedding_artists = df_train_embedding[df_train_embedding['title'].isin(artists)].mean()
embedding_sportsPerson = df_train_embedding[df_train_embedding['title'].isin(sportsPerson)].mean()
embedding_politicians = df_train_embedding[df_train_embedding['title'].isin(politicians)].mean()
embedding_scientists = df_train_embedding[df_train_embedding['title'].isin(scientists)].mean()
embedding_influencers = df_train_embedding[df_train_embedding['title'].isin(influencers)].mean()

In [30]:
W.shape

(25, 100)

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

In [32]:
for i in range(25):
    print(df_test['title'][i],round(cosine_similarity([W[i]], [embedding_artists])[0][0],2),
          round(cosine_similarity([W[i]], [embedding_sportsPerson])[0][0],2),
          round(cosine_similarity([W[i]], [embedding_politicians])[0][0],2),
          round(cosine_similarity([W[i]], [embedding_scientists])[0][0],2),
          round(cosine_similarity([W[i]], [embedding_influencers])[0][0],2))

abraham lincoln 0.19 0.19 0.75 0.49 0.26
atal bihari vajpayee 0.04 0.22 0.87 0.14 0.23
justin trudeau 0.25 0.27 0.76 0.25 0.39
stephen hawking 0.15 0.11 0.14 0.83 0.25
nelson mandela 0.21 0.2 0.73 0.38 0.27
mark zuckerberg 0.46 0.3 0.49 0.3 0.49
virat kohli 0.1 0.26 0.03 0.11 0.1
novak djokovic 0.0 0.81 0.01 0.0 0.0
cristiano ronaldo 0.28 0.31 0.24 0.09 0.03
max planck 0.05 0.11 0.18 0.89 0.16
niels bohr 0.09 0.14 0.18 0.86 0.26
elon musk 0.43 0.21 0.59 0.35 0.46
michael jordan 0.17 0.51 0.02 0.05 0.42
shah rukh khan 0.14 0.01 0.0 0.0 0.26
azim premji 0.22 0.21 0.26 0.22 0.5
marie curie 0.06 0.07 0.07 0.71 0.19
dhirubhai ambani 0.15 0.31 0.47 0.21 0.39
ms dhoni 0.08 0.42 0.02 0.02 0.23
brad pitt 0.59 0.12 0.02 0.02 0.16
louis pasteur 0.08 0.07 0.09 0.84 0.16
tom hanks 0.68 0.04 0.01 0.1 0.1
tom cruise 0.61 0.17 0.11 0.11 0.23
will smith 0.65 0.1 0.06 0.08 0.13
ernest rutherford 0.07 0.04 0.02 0.77 0.2
melinda gates 0.18 0.03 0.02 0.05 0.35


In [33]:
lst = []
for i in range(25):
    tmp = [df_test['title'][i]]
    v1 = cosine_similarity([W[i]], [embedding_artists])[0][0]
    v2 = cosine_similarity([W[i]], [embedding_sportsPerson])[0][0]
    v3 = cosine_similarity([W[i]], [embedding_politicians])[0][0]
    v4 = cosine_similarity([W[i]], [embedding_scientists])[0][0]
    v5 = cosine_similarity([W[i]], [embedding_influencers])[0][0]
    msum = v1 + v2 + v3 + v4 + v5
    tmp = tmp + [v1/msum,v2/msum,v3/msum,v4/msum,v5/msum]
    lst.append(tmp)
    
    
    
    
    

In [34]:
df_test_prediction = pd.DataFrame(lst, columns=['title','Artist','SportsPerson','Politician/Leader','Scientist/Researcher','Influencer'])

In [35]:
df_test_prediction.head()

title    Artist  SportsPerson  Politician/Leader  \
0       abraham lincoln  0.101903      0.100169           0.401469   
1  atal bihari vajpayee  0.024811      0.149144           0.578867   
2        justin trudeau  0.129074      0.140275           0.398779   
3       stephen hawking  0.103959      0.075064           0.093014   
4        nelson mandela  0.117387      0.112960           0.408801   

   Scientist/Researcher  Influencer  
0              0.260615    0.135844  
1              0.096371    0.150807  
2              0.129943    0.201930  
3              0.561536    0.166426  
4              0.211414    0.149438

In [400]:
# df_test_prediction.to_csv("Resultsrahul.csv",header=True,index=False)